/**
 * server/middleware/rbac.js — Role-Based Access Control (RBAC) Engine
 * Defines enterprise roles and granular permission matrices.
 */

const ROLES = {
  OWNER: 'OWNER',
  ADMIN: 'ADMIN',
  OPERATIONS: 'OPERATIONS',
  INVENTORY_MANAGER: 'INVENTORY_MANAGER',
  MARKETING: 'MARKETING',
  CUSTOMER_SUPPORT: 'CUSTOMER_SUPPORT',
  FINANCE: 'FINANCE',
  VIEWER: 'VIEWER'
};

const PERMISSIONS = {
  // Products & Pricing
  VIEW_PRODUCTS: 'VIEW_PRODUCTS',
  EDIT_PRODUCTS: 'EDIT_PRODUCTS',
  CHANGE_PRICE: 'CHANGE_PRICE',
  DELETE_PRODUCTS: 'DELETE_PRODUCTS',

  // Orders & Fulfillment
  VIEW_ORDERS: 'VIEW_ORDERS',
  UPDATE_ORDER_STATUS: 'UPDATE_ORDER_STATUS',
  MANAGE_SHIPPING_AWB: 'MANAGE_SHIPPING_AWB',
  CANCEL_ORDER: 'CANCEL_ORDER',
  PROCESS_REFUND: 'PROCESS_REFUND',

  // Customers & Privacy
  VIEW_CUSTOMERS: 'VIEW_CUSTOMERS',
  VIEW_CUSTOMER_PII: 'VIEW_CUSTOMER_PII', // Full phone & address
  EDIT_CUSTOMER: 'EDIT_CUSTOMER',

  // Inventory & Ledger
  VIEW_INVENTORY: 'VIEW_INVENTORY',
  ADJUST_INVENTORY: 'ADJUST_INVENTORY',
  VIEW_INVENTORY_LEDGER: 'VIEW_INVENTORY_LEDGER',
  MANAGE_BATCHES: 'MANAGE_BATCHES',

  // Approvals
  REQUEST_APPROVAL: 'REQUEST_APPROVAL',
  APPROVE_REQUESTS: 'APPROVE_REQUESTS',

  // Finance
  VIEW_FINANCIALS: 'VIEW_FINANCIALS',
  VIEW_REVENUE: 'VIEW_REVENUE',
  EXPORT_FINANCIAL_REPORT: 'EXPORT_FINANCIAL_REPORT',

  // Marketing & Content
  MANAGE_CONTENT: 'MANAGE_CONTENT',
  MANAGE_BLOGS: 'MANAGE_BLOGS',
  MANAGE_B2B: 'MANAGE_B2B',

  // Security & Audit
  VIEW_AUDIT_LOGS: 'VIEW_AUDIT_LOGS',
  MANAGE_ADMIN_USERS: 'MANAGE_ADMIN_USERS',
  MANAGE_SECURITY_SETTINGS: 'MANAGE_SECURITY_SETTINGS',
  PERFORM_SYSTEM_MAINTENANCE: 'PERFORM_SYSTEM_MAINTENANCE'
};

// Role-to-Permissions Mapping Matrix
const ROLE_PERMISSIONS = {
  [ROLES.OWNER]: Object.values(PERMISSIONS), // Full unchecked access
  
  [ROLES.ADMIN]: [
    PERMISSIONS.VIEW_PRODUCTS,
    PERMISSIONS.EDIT_PRODUCTS,
    PERMISSIONS.CHANGE_PRICE,
    PERMISSIONS.VIEW_ORDERS,
    PERMISSIONS.UPDATE_ORDER_STATUS,
    PERMISSIONS.MANAGE_SHIPPING_AWB,
    PERMISSIONS.CANCEL_ORDER,
    PERMISSIONS.PROCESS_REFUND,
    PERMISSIONS.VIEW_CUSTOMERS,
    PERMISSIONS.VIEW_CUSTOMER_PII,
    PERMISSIONS.EDIT_CUSTOMER,
    PERMISSIONS.VIEW_INVENTORY,
    PERMISSIONS.ADJUST_INVENTORY,
    PERMISSIONS.VIEW_INVENTORY_LEDGER,
    PERMISSIONS.MANAGE_BATCHES,
    PERMISSIONS.REQUEST_APPROVAL,
    PERMISSIONS.APPROVE_REQUESTS,
    PERMISSIONS.VIEW_FINANCIALS,
    PERMISSIONS.VIEW_REVENUE,
    PERMISSIONS.EXPORT_FINANCIAL_REPORT,
    PERMISSIONS.MANAGE_CONTENT,
    PERMISSIONS.MANAGE_BLOGS,
    PERMISSIONS.MANAGE_B2B,
    PERMISSIONS.VIEW_AUDIT_LOGS,
    PERMISSIONS.PERFORM_SYSTEM_MAINTENANCE
  ],

  [ROLES.OPERATIONS]: [
    PERMISSIONS.VIEW_PRODUCTS,
    PERMISSIONS.VIEW_ORDERS,
    PERMISSIONS.UPDATE_ORDER_STATUS,
    PERMISSIONS.MANAGE_SHIPPING_AWB,
    PERMISSIONS.VIEW_CUSTOMERS,
    PERMISSIONS.VIEW_CUSTOMER_PII,
    PERMISSIONS.VIEW_INVENTORY,
    PERMISSIONS.VIEW_INVENTORY_LEDGER,
    PERMISSIONS.MANAGE_BATCHES,
    PERMISSIONS.MANAGE_B2B
  ],

  [ROLES.INVENTORY_MANAGER]: [
    PERMISSIONS.VIEW_PRODUCTS,
    PERMISSIONS.VIEW_INVENTORY,
    PERMISSIONS.ADJUST_INVENTORY,
    PERMISSIONS.VIEW_INVENTORY_LEDGER,
    PERMISSIONS.MANAGE_BATCHES,
    PERMISSIONS.REQUEST_APPROVAL
  ],

  [ROLES.MARKETING]: [
    PERMISSIONS.VIEW_PRODUCTS,
    PERMISSIONS.EDIT_PRODUCTS,
    PERMISSIONS.MANAGE_CONTENT,
    PERMISSIONS.MANAGE_BLOGS,
    PERMISSIONS.MANAGE_B2B
  ],

  [ROLES.CUSTOMER_SUPPORT]: [
    PERMISSIONS.VIEW_PRODUCTS,
    PERMISSIONS.VIEW_ORDERS,
    PERMISSIONS.UPDATE_ORDER_STATUS,
    PERMISSIONS.VIEW_CUSTOMERS,
    PERMISSIONS.VIEW_CUSTOMER_PII,
    PERMISSIONS.MANAGE_B2B,
    PERMISSIONS.REQUEST_APPROVAL
  ],

  [ROLES.FINANCE]: [
    PERMISSIONS.VIEW_ORDERS,
    PERMISSIONS.VIEW_FINANCIALS,
    PERMISSIONS.VIEW_REVENUE,
    PERMISSIONS.PROCESS_REFUND,
    PERMISSIONS.EXPORT_FINANCIAL_REPORT,
    PERMISSIONS.VIEW_AUDIT_LOGS
  ],

  [ROLES.VIEWER]: [
    PERMISSIONS.VIEW_PRODUCTS,
    PERMISSIONS.VIEW_ORDERS,
    PERMISSIONS.VIEW_INVENTORY
  ]
};

function hasPermission(role, permission) {
  if (!role || !ROLE_PERMISSIONS[role]) return false;
  return ROLE_PERMISSIONS[role].includes(permission);
}

function requirePermission(permission) {
  return (req, res, next) => {
    const role = req.admin?.role || 'OWNER'; // Default to authenticated admin token role
    if (!hasPermission(role, permission)) {
      return res.status(403).json({
        error: `Access Denied: Role '${role}' lacks the required '${permission}' permission.`,
        requiredPermission: permission,
        currentRole: role
      });
    }
    next();
  };
}

module.exports = {
  ROLES,
  PERMISSIONS,
  ROLE_PERMISSIONS,
  hasPermission,
  requirePermission
};
